site_name: Unciv Mods
theme:
  name: material
  logo: assets/Icon.png
  favicon: assets/favicon.png

  palette:
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to Dark Mode
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to Light Mode

  icon:
    repo: fontawesome/brands/github

repo_name: robloach/unciv-mods
repo_url: https://github.com/robloach/unciv-mods
site_url: https://robloach.github.io/unciv-mods
markdown_extensions:
  # For adminitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.details # For collapsable admonitions - see https://squidfunk.github.io/mkdocs-material/reference/admonitions/?h=%3F%3F%3F#collapsible-blocks

  # For Abbreviations
  - abbr
  - pymdownx.snippets

plugins:
  - awesome-pages

extra_javascript:
  - https://unpkg.com/tablesort@5.6.0/dist/tablesort.min.js
  - https://unpkg.com/tablesort@5.6.0/dist/sorts/tablesort.number.min.js
  - javascripts/tablesort.js
